env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - binary: doggo
    id: cli
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "7"

  - binary: doggo-web.bin
    id: web
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./web/

archives:
  - id: cli
    allow_different_binary_count: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Others
      order: 999


dockers:
  - image_templates:
      - "ghcr.io/mr-karan/doggo:{{ .Tag }}"
      - "ghcr.io/mr-karan/doggo:latest"
    id: doggo
    # IDs to filter the binaries/packages.
    ids:
      - cli
    dockerfile: Dockerfile-cli
    build_flag_templates:
      - "--build-arg"
      - "ARCH=amd64"
  - image_templates:
      - "ghcr.io/mr-karan/doggo:{{ .Tag }}-arm64v8"
      - "ghcr.io/mr-karan/doggo:latest-arm64v8"
    id: doggo-arm
    # IDs to filter the binaries/packages.
    ids:
      - cli
    goarch: arm64
    dockerfile: Dockerfile-cli
    build_flag_templates:
      - "--build-arg"
      - "ARCH=arm64v8"
